version: '3.8'

services:
  app:
    build: .
    container_name: howmanycals
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./users.db:/app/users.db
    restart: unless-stopped
